### ISSUE TITLE
Installation of the bundle fails

### ISSUE THREAD

**Issue by xaviermarchegay** [cleverage/process-bundle#115]
## Description
`symfony new test --version=lts`
`cd test/`
`composer require cleverage/process-bundle`

## Result
Using version ^3.1 for cleverage/process-bundle
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Restricting packages listed in "symfony/symfony" to "4.4.*"

Prefetching 15 packages 🎶
  - Downloading (100%)

Package operations: 17 installs, 0 updates, 0 removals
  - Installing symfony/translation-contracts (v2.0.1): Loading from cache
  - Installing symfony/translation (v4.4.5): Loading from cache
  - Installing symfony/validator (v4.4.5): Loading from cache
  - Installing symfony/options-resolver (v4.4.5): Loading from cache
  - Installing symfony/inflector (v4.4.5): Loading from cache
  - Installing symfony/property-access (v4.4.5): Loading from cache
  - Installing symfony/intl (v4.4.5): Loading from cache
  - Installing symfony/polyfill-intl-icu (v1.14.0): Loading from cache
  - Installing symfony/form (v4.4.5): Loading from cache
  - Installing sidus/base-bundle (v1.1.1): Loading from cache
  - Installing symfony/serializer (v4.4.5): Loading from cache
  - Installing symfony/process (v4.4.5): Loading from cache
  - Installing monolog/monolog (1.25.3): Loading from cache
  - Installing symfony/monolog-bridge (v4.4.5): Loading from cache
  - Installing symfony/monolog-bundle (v3.5.0): Loading from cache
  - Installing symfony/expression-language (v4.4.5): Loading from cache
  - Installing cleverage/process-bundle (v3.1.0): Loading from cache
Writing lock file
Generating autoload files
Symfony operations: 5 recipes (44f62a23527369519fd93a30a9962a57)
  - Configuring symfony/translation (>=3.3): From github.com/symfony/recipes:master
  - Configuring symfony/validator (>=4.3): From github.com/symfony/recipes:master
  - Configuring sidus/base-bundle (>=v1.1.1): From auto-generated recipe
  - Configuring symfony/monolog-bundle (>=3.3): From github.com/symfony/recipes:master
  - Configuring cleverage/process-bundle (>=v3.1.0): From auto-generated recipe
Executing script cache:clear [KO]
 [KO]
Script cache:clear returned with error code 1
!!  
!!  In ArrayNode.php line 224:
!!                                                                                 
!!    The child node "default_error_strategy" at path "clever_age_process" must b  
!!    e configured.                                                                
!!                                                                                 
!!  
!!  
Script @auto-scripts was called via post-update-cmd

**Comment by shavounet** [comment]
It's intended to force `default_error_strategy` definition. This was decided to avoid a silent BC break after a change of default behavior...

Maybe it can have a default value of `stop` in next major version ?

**Comment by njoubert-cleverage** [comment]
Release V2.0 have an information/BC break about it on CHANGELOG.
