### ISSUE TITLE
Add support for PHPStan

### ISSUE THREAD

**Issue by shavounet** [cleverage/process-bundle#122]
## Description

Add a configuration file for [PHPStan](https://phpstan.org/), use a high as possible level, fix what's needed, add it to CI.

## Requirements

* Documentation updates
  - [ ] Reference
  - [ ] Cookbooks
  - [ ] Changelog
* [ ] Unit tests

**Comment by njoubert-cleverage** [comment]
Treated by https://github.com/cleverage/process-bundle/issues/139.
