### ISSUE TITLE
Composer.json: "replace" should not be used in vendors

### ISSUE THREAD

**Issue by VincentChalnot** [cleverage/process-bundle#129]
https://github.com/cleverage/process-bundle/blob/78276bb5fedb01b222c4261ba6bfd01a5b892aca/composer.json#L50

https://getcomposer.org/doc/04-schema.md#replace

When installing alongside an other vendor or in a project that is already "replacing" the same package, installation will crash:
```
cleverage/process-bundle[dev-v4-dev, v4.0.0] cannot be installed as that would require removing *****/*****. They both replace symfony/polyfill-ctype and thus cannot coexist.
```

**Comment by njoubert-cleverage** [comment]
Fixed it on future v4.0 version.
