### ISSUE TITLE
Error: bad implementation for InstantiateTransformer

### ISSUE THREAD

**Issue by curtisrye** [cleverage/process-bundle#133]
## Description

Method `transform` for `InstantiateTransformer` should have a non-typed `$value`to be complient with `TransformerInterface`

## Requirements

* Documentation updates
  - [ ] Reference
  - [ ] Cookbooks
  - [ ] Changelog
* [ ] Unit tests

**Comment by tonongregory** [comment]
Just push a fix on v3.2-dev branch 
https://github.com/cleverage/process-bundle/commit/5e0464a42658a3441962d44b12437524e598110d
