### ISSUE TITLE
An error is throw if no tasks are defined (like in the documentation)

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/process-bundle#75]
An error is throw if no tasks are defined :

```php
    # \CleverAge\ProcessBundle\Configuration\ProcessConfiguration
    /** @var array */
    protected $mainTaskGroup;
```
to replace by :

```php
    # \CleverAge\ProcessBundle\Configuration\ProcessConfiguration
    /** @var array */
    protected $mainTaskGroup = [];
```

The bug is not very annoying as job without task has no worth, but this is the documentation example. In my opinion,  documentation examples should work out-of-the box.

Note : As the `$mainTaskGroup` is an array, it should be called `$mainTaskGroups`.

**Comment by shavounet** [comment]
Fixed
