### ISSUE TITLE
Configuration does not allow to be split in several files

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/process-bundle#81]
When trying to separate configuration into several files, the following error happens :

```
Configuration path "clever_age_process.generic_transformers.my_transformers" cannot be overwritten. You have to define all   
  options for this path, and any of its sub-paths in one configuration section.   
```

The goal was to separate the generic transformers configuration from the jobs configuration.

This forces the developer to keep the process configuration in one big file...

**Comment by shavounet** [comment]
One transformer definition cannot be split (here `my_transformers`), but you should be able to have multiple files for `clever_age_process.generic_transformers`.

Can you check and try again ?

**Comment by johnkrovitch** [comment]
Yes the bug is still present.

**Comment by shavounet** [comment]
Tested together and ok
