### ISSUE TITLE
Is it possible to handle several Datetime format ?

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/process-bundle#85]
I need to handle several date formats in a single process, is it possible ?

I do not find the documentation about that ?

(@shavounet) TODO
* [x] documentation

**Comment by johnkrovitch** [comment]
Fix comment in CleverAge\ProcessBundle\Transformer\DateParserTransformer "output aa \DateTime"

**Comment by shavounet** [comment]
Already possible through `\CleverAge\ProcessBundle\Transformer\DateParserTransformer`

=> TODO documentation
