### ISSUE TITLE
Cleanup & move the help command into an independant bundle

### ISSUE THREAD

**Issue by shavounet** [cleverage/process-bundle#93]
## Description

Move the graph displaying feature into an external bundle, and only use it here.

**Comment by njoubert-cleverage** [comment]
cleverage:process:help Command is an important part of ProcessBundle, contained on only 1 file, without external dependencies. So another bundle -to maintain- is not a good thing.

**Comment by shavounet** [comment]
My original idea was to create a standalone "graph cli" tool to be able to reuse it elsewhere :) Feel free to adapt !
_though that "help" command is not a piece of art, have some bug and should be reworked_ :sweat_smile:
