### ISSUE TITLE
Deprecated : remove string input / false output from DateFormatTransformer

### ISSUE THREAD

**Issue by shavounet** [cleverage/process-bundle#95]
## Description

Remove deprecated behavior in `DateFormatTransformer`

## Requirements

* Documentation updates
  - ~Reference~
  - [ ] Changelog
* [ ] Unit tests 

## Breaking changes

* minor: `date_format` transformer will not accept `string` input anymore
* minor: `date_format` transformer will throw errors on failed output instead of returning `false`

**Comment by xaviermarchegay** [comment]
Done in the v4 branch.

Exception if a DateTimeInterface is not passed to the transformer: https://github.com/cleverage/process-bundle/blob/v4-dev/src/Transformer/DateFormatTransformer.php#L35

Unit tests : https://github.com/cleverage/process-bundle/blob/v4-dev/tests/Transformer/DateParserTransformerTest.php#L40
