### ISSUE TITLE
Nested exceptions in transformers are not logged

### ISSUE THREAD

**Issue by johnkrovitch** [cleverage/process-bundle#99]
## Description

If a transformer throws a exception, the transformer trait will catch and throw an other exception containing the previous one. Unfortunately, the inner exception is not logged, which make things very difficult to debug when an error happens in a nested transformer.

**Comment by shavounet** [comment]
I've checked the code, added a test and improved the message, but nested error should be pushed upward. Feel free to reopen it if you have additional details.
